# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript,....

trigger:
- master

variables:
  # Environment name
  environmentName: 'NodeAppGH'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

resources:
  repositories:
  - repository: 'GHConnect'   
    type: GitHub
    connection: '3121f8f4-e7d6-47f6-855d-299414956cba'
    source: 'RoopeshNair/nodeApp'
    ref: 'refs/heads/master'

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:            
          - checkout: self
          - checkout: GHConnect
